unsigned short dataLength(char protocol);
unsigned short messageLength(char protocol);
char* header(char protocol, char transportLayer);
char* dataProtocol00();
char* dataProtocol0();
char* dataProtocol1();
char* dataProtocol2();
char* dataProtocol3();
char* dataProtocol4();
char* mensaje(char protocol, char transportLayer);
void ESP_LOGI(const char* a, char* data, int* len, int err);
void ESP_LOGE(const char* a, char* data, int* len, int err);