float floatrand(float lower, float max);
int int_rand(int lower, int upper);
float * accelometer_sensor_x();
float * accelometer_sensor_y();
float * accelometer_sensor_z();
char thcp_temp_sensor();
char thcp_hum_sensor();
float thcp_pres_sensor();
float thcp_CO_sensor();
char batt_sensor();
float accelerometer_kpi_amp_x();
float accelerometer_kpi_frec_x();
float accelerometer_kpi_amp_y();
float accelerometer_kpi_frec_y();
float accelerometer_kpi_amp_z();
float accelerometer_kpi_frec_z();
float rms();